language: c

os:
  - linux

compiler:
  - gcc
  - clang

before_script:
  - pip3 install --user cpplint


script:
  - gcc -std=c11  -c ./libstat.c
  - ar r libstat.a libstat.o
  - gcc -std=c11 -c -fPIC libdyn.c
  - gcc -shared -o libdyn.so libdyn.o
  - gcc -std=c11 --coverage -c *.c
  - gcc -o Homework2 *.o -fprofile-arcs -ftest-coverage -g -L. -ldyn -lstat -Wl,-rpath,.
   - ./Homework2

  - lcov -t "coverage" -o coverage.info -c -d .
  - cpplint --filter=-readability,-build *.c
  - cppcheck --enable=warning,performance,information,style *.c *.h
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - lcov
      - cppcheck
      - valgrind
      - make
      - cmake
    update: true
