language: c

os:
  - linux

compiler:
  - gcc
  - clang

before_script:
  - pip3 install --user cpplint


script:
  - gcc -c ./stat_lib.c
  - ar r libstat.a stat_lib.o
  - rm *.o
  - gcc -o Homework2App stat_lib.o -lstat
  - lcov -t "coverage" -o coverage.info -c -d .
  - cpplint --filter=-readability,-build *.c
  - cppcheck --enable=warning,performance,information,style *.c *.h
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - lcov
      - cppcheck
      - valgrind
      - make
      - cmake
    update: true
