language: c

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

before_script:
  - pip3 install --user cpplint


script:
  - gcc main.c -L. -pthread -g -Wall -Wextra -o main
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - cppcheck
      - valgrind
      - make
      - cmake
    update: true
