language: c

os:
  - linux

compiler:
  - gcc
  - clang

before_script:
  - pip3 install --user cpplint


script:
  - gcc main.c static_library/stat_lib.h static_library/stat_lib.c dynamic_library/dyn_lib.h dynamic_library/dyn_lib.c -g -Wall -Wextra -o main
  - gcc -L. -pthread
  - cpplint --filter=-readability,-build *.c ; fi
  - cppcheck --enable=warning,performance,information,style *.c *.h ; fi
  - genhtml -o report coverage.info ; fi
  - valgrind --leak-check=full --show-leak-kinds=all ./Homework2 ;
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - cppcheck
      - valgrind
      - make
      - cmake
    update: true
