language: c

os:
  - linux

compiler:
  - gcc
  - clang

before_script:
  - pip3 install --user cpplint


script:
  - gcc -std=c11 -c ./ *.c
  - ar r libstat.a *.o
  - gcc -std=c11 -c -fPIC ./*.c
  - gcc -shared -o libdyn.so *.o
  - gcc -std=c11 -c *.c
  - gcc -o Homework2 *.o -L. -ldyn -lstat -lpthread -Wl,-rpath,.
  - ./Homeworks2
  - lcov -t "coverage" -o coverage.info -c -d .
  - cpplint --filter=-readability,-build *.c
  - cppcheck --enable=warning,performance,information,style *.c *.h
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - lcov
      - cppcheck
      - valgrind
      - make
      - cmake
    update: true
