language: c

os:
  - linux

compiler:
  - gcc
  - clang

before_script:
  - pip3 install --user cpplint


script:
  - gcc -std=c11 -c ./static_library/*.c
  - ar r libstatic.a *.o
  - gcc -std=c11 -c -fPIC static_library/*.c
  - gcc -shared -o libdynamic.so *.o
  - gcc -std=c11 -c *.c
  - gcc -o application *.o -L. -lstat
  - ./application
  - lcov -t "coverage" -o coverage.info -c -d .
  - cpplint --filter=-readability,-build *.c
  - cppcheck --enable=warning,performance,information,style *.c *.h
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - lcov
      - cppcheck
      - valgrind
      - make
      - cmake
    update: true
