/*
 * "Copyright 2019 Sergei Petrenko"
 */

#ifndef DESKTOP_HOMEWORK2_STATIC_LIBRARY_STAT_LIB_H_
#define DESKTOP_HOMEWORK2_STATIC_LIBRARY_STAT_LIB_H_

#endif  // DESKTOP_HOMEWORK2_STATIC_LIBRARY_STAT_LIB_H_
