/*
 * "Copyright 2019 Sergei Petrenko"
 */

#ifndef DESKTOP_HOMEWORK2_DYNAMIC_LIBRARY_DYN_LIB_H_
#define DESKTOP_HOMEWORK2_DYNAMIC_LIBRARY_DYN_LIB_H_

#endif  // DESKTOP_HOMEWORK2_DYNAMIC_LIBRARY_DYN_LIB_H_
